name: React CI Pipeline

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build


deploy-dev:
  needs: build-test
  if: github.ref == 'refs/heads/dev'
  runs-on: ubuntu-latest
  steps:
    - name: Deploy to Development
      run: |
        echo "Deploying to Dev environment..."
        # Example for Vercel:
        npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm
        # Or for Netlify:
        # npx netlify deploy --dir=build --prod --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }}