name: CD - Deploy React App

on:
  push:
    branches: ["main", "dev"]

jobs:
  deploy-dev:
    name: Deploy Dev Branch
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: ./build

      - name: Deploy to GitHub Pages (dev)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          destination_dir: dev   # deploys to /dev

  deploy-main:
    name: Deploy Main Branch
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: ./build

      - name: Deploy to GitHub Pages (main)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          # deploys to root (/)
